## Network

```
X         W
[[1, 2, 3, n]       [[1 2 3 4]
 [1, 2, 3, n]        [1 2 3 4]
 [1, 2, 3, n]        [1 2 3 4]
 [1, 2, 3, n]]        [1 2 3 4]]
```


In [30]:
import numpy as np

X = np.array([
    [
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]
    ],
    [
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]
    ]
])

The matrix X is an array of matrices.
The shape is `(2, 3, 4)` which means:
  * 2 matrices of
  * 3 rows of 4 columns

In [31]:
print(X.shape)

(2, 3, 4)


What we want is to pressent each row as a column, i.e

```
[[1, 2, 3, n]
 [1, 2, 3, n]
 [1, 2, 3, n]
 [1, 2, 3, n]]
```

In [32]:
print(X[0].T)
print(X[0].T.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
(4, 3)


This is a `(4, 3)` matix, the weight should be a `(3, 4)` matrix.

```
[1 2 3 ...]
[1 2 3 ...]
[1 2 3 ...]
```

i.e `(3, m)`

X.dot(W)

In [33]:
W = np.array([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])

print(W.shape)

(3, 4)


X is a (m, 4) matrix

In [40]:
X_1 = X[0].T
# importtant that W is first
A_1 = np.dot(W, X_1)
print(X_1)
print(W)
print(A_1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 4  8 12]
 [ 4  8 12]
 [ 4  8 12]]
